language: go
go:
  - "1.11"
  - "1.11.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - 1156143589@qq.com
    on_success: change # default: change
    on_failure: always # default: always

before_script:
  - echo "Hello World"

script:
  - echo "Hello PddCrawler"




